/* Build the bundled-icon map from the bootstrap-icons package SVGs.
   Run when the curated lists change: `npm run gen-icons`.
   Emits src/icons.bundled.js as { 'bi:<name>': '<svg-data-uri>' }. */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { BI_ICONS, CHROME_ICONS } from '../src/icon-list.js';

const here = dirname(fileURLToPath(import.meta.url));
const iconDir = resolve(here, '../node_modules/bootstrap-icons/icons');

const names = [...new Set([...BI_ICONS, ...CHROME_ICONS])].sort();

// Compact SVG->data-URI: single-quote attrs (apostrophes survive
// encodeURIComponent raw) and restore chars that are safe inside a quoted
// CSS url(). Roughly a third smaller than a plain encodeURIComponent.
function dataUri(svg) {
	const enc = encodeURIComponent(svg.replace(/"/g, "'"))
		.replace(/%20/g, ' ').replace(/%2F/g, '/').replace(/%3D/g, '=')
		.replace(/%3A/g, ':').replace(/%2C/g, ',');
	return 'data:image/svg+xml,' + enc;
}

const entries = names.map(name => {
	let svg = readFileSync(resolve(iconDir, `${name}.svg`), 'utf8');
	// Drop the source class attr and collapse whitespace; the mask ignores fill,
	// but viewBox + paths are what we need.
	svg = svg.replace(/\sclass="[^"]*"/, '').replace(/\s*\n\s*/g, '').trim();
	return `\t'bi:${name}': "${dataUri(svg)}"`;
});

const out =
`/* GENERATED by scripts/gen-icons.mjs - do not edit by hand.
   Curated Bootstrap Icons inlined as SVG data URIs for offline use. */

/** @type {Record<string, string>} */
export const BUNDLED_ICONS = {
${entries.join(',\n')}
};
`;

writeFileSync(resolve(here, '../src/icons.bundled.js'), out);
console.log(`Wrote src/icons.bundled.js (${names.length} icons)`);
